### ISSUE TITLE
Dokumentacja końcowa

### ISSUE THREAD

**Issue by KowalskiPiotr98** [KowalskiPiotr98/access.analyser#26]
opis
architektura
użyte technologie
krótka instrukcja użytkownika 
instrukcja postawienia aplikacji na AWS
zmiany względem dokumentacji wstepnej
wnioski / podsumowanie

**Comment by KowalskiPiotr98** [comment]
@k1kli Wrzuciłem na branch FinalDoc dokumentację końcową, ale zostawiłem pusty kawałek z instrukcją postawienia na AWS. Mógłbyś tam dopisać parę zdań, bo Ty chyba wiesz najlepiej jak to działa.

**Comment by KowalskiPiotr98** [comment]
> @k1kli Wrzuciłem na branch FinalDoc dokumentację końcową, ale zostawiłem pusty kawałek z instrukcją postawienia na AWS. Mógłbyś tam dopisać parę zdań, bo Ty chyba wiesz najlepiej jak to działa?

Napiszę coś w tym punkcie sam, ale potem potwierdź czy jest ok.

**Comment by KowalskiPiotr98** [comment]
![image](https://user-images.githubusercontent.com/56399446/83746220-1608c980-a65f-11ea-8b23-f6cc6c1b3177.png)
Taki błąd dostałem w momencie stawiania `s3lambda.template`

**Comment by KowalskiPiotr98** [comment]
[access.analyser.pdf](https://github.com/KowalskiPiotr98/access.analyser/files/4729445/access.analyser.pdf)
@k1kli @SirMathelot zobaczcie czy jest ok i zgłoście ewentualne uwagi

**Comment by SirMathelot** [comment]
dla mnie ok
