### ISSUE TITLE
Panel administratora

### ISSUE THREAD

**Issue by KowalskiPiotr98** [KowalskiPiotr98/access.analyser#6]
- [x] dostęp tylko dla użytkowników w roli "Admin"
- [x] wylistowanie wszystkich użytkowników
- [x] osobny widok listujący użytkowników w klasie "Admin"
- [x] możliwość dodania i usunięcia użytkownika z klasy "Admin"
- [x] możliwość usunięcia konta użytkownika

**Comment by SirMathelot** [comment]
o co Ci chodziło w 3 i 4 punkcie?

**Comment by KowalskiPiotr98** [comment]
> o co Ci chodziło w 3 i 4 punkcie?

Zarządzanie użytkownikami z rolą "Admin" - lista użytkowników należących do tej roli i możliwość dodawania i usuwania użytkowników z tej roli.
Tam zamiast "klasa" powinienem "rola" napisać, mój błąd.

**Comment by SirMathelot** [comment]
Nie wiem po co osobny widok do tego. Mogę dodać jakieś sortowanie po roli albo przemianowanie na admina jakiegoś usera.

**Comment by KowalskiPiotr98** [comment]
> Nie wiem po co osobny widok do tego. Mogę dodać jakieś sortowanie po roli albo przemianowanie na admina jakiegoś usera.

No osobny widok nie jest konieczny, może być sortowanie albo jakiś filtr, na przykład.
No i dodanie/usunięcie z roli też może być po prostu zwykłym guzikiem w indeksie.

**Comment by KowalskiPiotr98** [comment]
> > Nie wiem po co osobny widok do tego. Mogę dodać jakieś sortowanie po roli albo przemianowanie na admina jakiegoś usera.
> 
> No osobny widok nie jest konieczny, może być sortowanie albo jakiś filtr, na przykład.
> No i dodanie/usunięcie z roli też może być po prostu zwykłym guzikiem w indeksie.

Jak postępy? Jeśli masz z czymś problem to pytaj.

**Comment by SirMathelot** [comment]
> > > Nie wiem po co osobny widok do tego. Mogę dodać jakieś sortowanie po roli albo przemianowanie na admina jakiegoś usera.
> > 
> > 
> > No osobny widok nie jest konieczny, może być sortowanie albo jakiś filtr, na przykład.
> > No i dodanie/usunięcie z roli też może być po prostu zwykłym guzikiem w indeksie.
> 
> Jak postępy? Jeśli masz z czymś problem to pytaj.

Już prawie skończyłem, zaraz wrzucę.
